# Generated by Django 4.2.7 on 2026-05-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MigratemateScraperState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('stopped', 'Stopped')], default='idle', max_length=20)),
                ('current_keyword', models.CharField(blank=True, max_length=200)),
                ('current_page', models.PositiveIntegerField(default=1)),
                ('keyword_index', models.PositiveIntegerField(default=0)),
                ('jobs_saved', models.PositiveIntegerField(default=0)),
                ('jobs_skipped', models.PositiveIntegerField(default=0)),
                ('processed_ids', models.TextField(blank=True, default='')),
                ('last_message', models.CharField(blank=True, max_length=500)),
                ('worker_pid', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'MigrateMate scraper state',
            },
        ),
        migrations.CreateModel(
            name='MigratemateJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('apply_url', models.URLField(max_length=2000, unique=True)),
                ('source', models.CharField(default='MigrateMate', max_length=100)),
                ('keyword', models.CharField(max_length=200)),
                ('posted_time', models.CharField(max_length=100)),
                ('posted_at', models.PositiveIntegerField(db_index=True, default=0)),
                ('migratemate_job_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'title', 'location'], name='migratemate_company_12d755_idx')],
            },
        ),
    ]
